### ISSUE TITLE
Error after v 0.22.2 or 0.22.3

### ISSUE THREAD

**Issue by H4Z4RD-H42** [ppfeufer/eve-online-killboard-widget#33]
I get this error when adding the widget to sidebar.

![image](https://user-images.githubusercontent.com/6650832/45318209-7c20f500-b53c-11e8-9fc8-b586abb48854.png)

I can't write nothing inside widget because this error show up immediatly.

**Comment by ppfeufer** [comment]
Give me a sec to straighten that one out, it's just the wrong remote helper that is being called ...

**Comment by ppfeufer** [comment]
So, that should do the trick, sorry for that.

**Comment by H4Z4RD-H42** [comment]
work great, thank you!

**Comment by ppfeufer** [comment]
Wonderful, closing this one than.
