### ISSUE TITLE
Wrong corp is shown

### ISSUE THREAD

**Issue by datasurgeservers** [ppfeufer/eve-online-killboard-widget#59]
action: get-eve-killboard-widget-data
type: corporation
name: Enemy Of Man
id: null
count: 5
showLosses: 1

(from your post in discord)

**Comment by ppfeufer** [comment]
CorpID is not resolved, for what ever reason, need to investigate.

**Comment by ppfeufer** [comment]
``Enemy Of Man`` is what you enter in the widget's settings
``Enemy of Man`` is the actual name of your corp, according to Esi

``Of`` vs. ``of``
Uppercase vs. lowecase, that's two different things, two different words if compared ...

"Fix" is in development branch, will be rolled out as soon as there is more to deploy which justifies a new version. In the meantime I suggest that you write your corp name correct in the settings.

**Comment by ppfeufer** [comment]
Fixed in new release
