### ISSUE TITLE
Image size wrong

### ISSUE THREAD

**Issue by scull2014** [ppfeufer/eve-online-killboard-widget#9]
Hi great widget but the images are about 50% bigger than they should be on my theme meaning text and images overlap.My theme does use bootstrap so not sure why.Hope you can help.

**Comment by scull2014** [comment]
I solved it by loading in your theme then inspecting I was missing 
img{
  max-width: 100%;}
in my css

**Comment by ppfeufer** [comment]
Good point, I'll add that to the plugins css as well ...
